---
title: "happiness index starter"
author: "Alexander Galvan, Calvin Peloso"
date: "2025-11-20"
output: html_document
---

```{r Setup}
library(dplyr)
library(ggplot2)
library(olsrr)
library(car)
library(psych)
```

```{r Base Model Building and Testing}
#Country: the name of the country
#Year: the year of the report (from 2005 to 2021)
#Life Ladder
#GDP per capita: the gross domestic product per capita in purchasing power parity (PPP) adjusted dollars.
#Social support: the perceived social support (ability to count on others) in the country
#Freedom to make life choices: the perceived freedom to make life choices in the country.
#Generosity: the perceived generosity of people in the country.
#Perceptions of corruption: the perceived level of corruption in the government and business sectors #of the country.

happiness <- read.csv("World Happiness Report 2005-2021.csv")

happiness |>  #166 different countries
  group_by(country = Country.name) |>
  count()

describe(happiness) #Confidence.in.national.government missing 216 obs, Perceptions.of.corruption missing 113 obs, also others.

happiness <- na.omit(happiness) #Removed NAs to allow for anova reduced model comparison

scatterplotMatrix(happiness[, c(2,4:12)]) #Some variables show patterns of interaction 

timeladder <- lm(Life.Ladder~Year+Log.GDP.per.capita+Social.support+Healthy.life.expectancy.at.birth+Freedom.to.make.life.choices+Generosity+Perceptions.of.corruption+Positive.affect+Negative.affect+Confidence.in.national.government,data=happiness) #Negative affect not significant after other predictors already baked in, R Squared = 0.787, F-statistic 641.1 on 10 and 1736 DF with P-value < 2.2e-16

summary(timeladder)

anova(timeladder) #Analysis of Variance and Type-1 p-values

vif(timeladder) #No values above 10

X <- model.matrix(timeladder)
cor(X) #Checks correlations between predictors, hinting that there may be significant interactions between Log.GDP.per.capita and Social.support (0.703) and Healthy.life.expectancy.at.birth (0.829), between Social.support and Healthy.life.expectancy.at.birth (0.612), and between Freedom.to.make.life.choices and Positive.affect (0.578)

# ^ Possible starting point for multi-collinearity investigation

XnoNAs <- X[-1, -1]
as.data.frame(cor(XnoNAs)) |>
  summarise(across(everything(), mean)) #Taking out the NAs (intercept from the X matrix) and averaging across predictor correlations, we find that Freedom.to.make.life.choices has the highest average correlation, followed by Healthy.life.expectancy.at.birth, Social.support, then Log.GDP.per.capita.
```

```{r Base Model Diagnostic and Prediction Plots}
happiness |>
  ggplot(aes(x = predict(timeladder), y = Life.Ladder)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  labs(x = 'Predicted Values', y = 'Actual Values')

qqnorm(timeladder$residuals) #Plots raw residual quantiles against theoretical normal distribution

residualPlot(timeladder) #Plots standardized residuals ([y - y_hat] / sqrt(Var)) against fitted

leverage_values <- hatvalues(timeladder)

plot(leverage_values, type = "h", main = "Leverage Values",
     xlab = "Observation Index", ylab = "Leverage")
abline(h = 2 * mean(leverage_values), col = "red", lty = 2) #Add a reference line for high leverage

ols_plot_resid_fit(timeladder) #Another residual vs fitted plot

plot(timeladder, which = 5) #Residuals vs Leverage plot
```

```{r Base Model AV Plots} 
avPlots(timeladder) #Reinforces ideas for reduced model, sweeping insignificant variables (low correlation, slope = 0, Year, Generosity) and near insignificant with high predictor correlation (Freedom.to.make.life.choices)
```


```{r OLS Model Building from base}
#OLS Steps with AIC metric (Long outputs)

ols_step_forward_aic(timeladder, details = TRUE) #Removes Negative.affect

ols_step_backward_aic(timeladder, details = TRUE) #Removes Negative.affect as well

ols_step_both_aic(timeladder, details = TRUE) #Also removes Negative.affect

#Negative.affect removal might indicate information is already captured i.e. by Positive.affect
#Also tells us  which features consistently make the bottom of the list, and/or offer the least amount of information per inclusion.
```

```{r Subset Testing from base}
timeladder_reduced <- lm(Life.Ladder~Log.GDP.per.capita+Social.support+Healthy.life.expectancy.at.birth+Perceptions.of.corruption+Positive.affect+Confidence.in.national.government,data=happiness) #Removed Year, Generosity, Freedom.to.make.life.choices, and Negative.affect. Also removes 308 observations.

summary(timeladder_reduced) #All Type-3 p-values insignificant, R Squared = 0.777, F-statistic 1031 on 6 and 1774 DF with P-value < 2.2e-16

anova(timeladder_reduced, timeladder) #While the pvalue is significant, which implies that the full model is better not due to chance (R squares 0.787 vs. 0.777), the partial f test also shows that only 24.5 sums of squares is reduced by the full model with an additional 4 degrees of freedom. Invoking parsimony, we can say that the reduced model is better.
```

```{r Subset Diagnostics and Prediction}
happiness |>
  ggplot(aes(x = predict(timeladder_reduced), y = Life.Ladder)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1) +
  labs(x = 'Predicted Values', y = 'Actual Values')

qqnorm(timeladder_reduced$residuals)

residualPlot(timeladder_reduced)

leverage_values_subset <- hatvalues(timeladder_reduced)
    
plot(leverage_values_subset, type = "h", main = "Leverage Values",
     xlab = "Observation Index", ylab = "Leverage")
abline(h = 2 * mean(leverage_values_subset), col = "red", lty = 2) #Add a reference line for high leverage

ols_plot_resid_fit(timeladder_reduced) 

plot(timeladder_reduced, which = 5) 
```


```{r Potential LASSO from base}

```

